
# SEO settings
title: "Talip Korkmaz Blog"
title2: "space" # default: ""
description: "Talip Korkmaz personal blog."
keywords: "talip korkmaz,talip korkmaz blog, java, spring, docker, SEO, blog, web, minimalist, thinkspace"
url: http://talipkorkmaz.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Talip Korkmaz"
  job      : "Software manager/architect/developer."
  bio      : "Developing with passion for equality and transformation of world"
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : http://heiswayi.github.io
  github   : https://github.com/talipkorkmaz
  twitter  : http://twitter.com/HeiswayiNrird
  facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/nrird
  stackoverflow : http://stackoverflow.com/users/1530849/talipkorkmaz

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
